import type { ProgramConfig } from "./types";

export const corporateConfig: ProgramConfig = {
  programKey: "corporate",
  programDomain: "streamline-corporate",
  appName: "StreamLine Corporate",
  shortName: "CORPORATE",
  tagline: "The professional communications platform for modern organizations",
  defaultRouteAfterLogin: "/streamline/corporate/dashboard",
  publicLandingRoute: "/streamline/corporate",
  enabledRoutes: [
    "dashboard",
    "chat",
    "calls",
    "broadcasts",
    "training",
    "documents",
    "directory",
    "org-chart",
    "analytics",
    "members",
    "company",
    "settings",
  ],
  features: {
    canUseClassrooms: false,
    canUseCourses: false,
    canUseDepartments: true,
    canUseCorporateRooms: true,
    canUseTeams: true,
    canUseWebinars: true,
    canUseGreenroom: false,
    canUseIntroClip: false,
    canUseRecordingLibrary: false,
    canUsePayPerView: false,
    canUseAdminUsage: true,
    canUseSupportHub: false,
    canCustomizeRooms: false,
  },
  billingProductKey: "streamline_corporate",
  backendProgramHeader: "streamline-corporate",
};
