import type { ProgramConfig } from "./types";

export const eduConfig: ProgramConfig = {
  programKey: "edu",
  programDomain: "streamline-edu",
  appName: "StreamLine EDU",
  shortName: "EDU",
  tagline: "The learning experience platform for modern schools",
  defaultRouteAfterLogin: "/streamline/edu/dashboard",
  publicLandingRoute: "/streamline/edu",
  enabledRoutes: [
    "dashboard",
    "broadcast",
    "events",
    "embed",
    "rooms",
    "people",
    "chat",
    "calls",
    "media-library",
    "support",
    "settings",
  ],
  features: {
    canUseClassrooms: true,
    canUseCourses: true,
    canUseDepartments: false,
    canUseCorporateRooms: false,
    canUseTeams: false,
    canUseWebinars: true,
    canUseGreenroom: false,
    canUseIntroClip: false,
    canUseRecordingLibrary: true,
    canUsePayPerView: false,
    canUseAdminUsage: true,
    canUseSupportHub: true,
    canCustomizeRooms: true,
  },
  supportHubProgramId: "edu",
  billingProductKey: "streamline_edu",
  backendProgramHeader: "streamline-edu",
};
